Attribute VB_Name = "Strs"
Public rebootvbpo As String
Public language_reboot As String
Public weekday_ As String

Public cmd_help As String
Public cmd_help_help As String
Public cmd_help_exec As String
Public cmd_help_reboot As String
Public cmd_help_exit As String
Public cmd_help_run As String
Public cmd_help_clear As String
Public cmd_help_version As String
Public cmd_help_about As String
Public cmd_help_time As String
Public cmd_help_copy As String
Public cmd_help_delete As String
Public cmd_help_makedir As String
Public cmd_help_hide As String
Public cmd_help_read As String
Public cmd_help_write As String

Public cmd_about As String
Public cmd_version As String
Public cmd_about_vbpo As String
Public cmd_about_phppo As String
Public cmd_about_javapo As String
Public cmd_about_hsppo As String
Public cmd_about_naohisss As String
Public cmd_time As String
Public cmd_time_time As String
Public cmd_time_date As String
Public cmd_time_year As String
Public cmd_time_weekday As String

Public err_unknowncommand As String
Public err_unknownparameter As String
Public err_exec As String
Public err_run_1 As String
Public err_run_2 As String
Public err_reboot As String
Public err_exit As String
Public err_help As String
Public err_copy As String
Public err_delete As String
Public err_makedir As String
Public err_hide As String
Public err_read As String
Public err_write As String

Public suc_exec As String
Public suc_run As String
Public suc_reboot As String
Public suc_exit As String
Public suc_copy As String
Public suc_delete As String
Public suc_makedir As String
Public suc_hide As String
Public suc_read As String
Public suc_write As String
